### ISSUE TITLE
Check Strong's numbers for divineNames

### ISSUE THREAD

**Issue by lemtom** [lemtom/statenvertaling#11]
cf. I observe that within CrossWire's source text for the flagship **KJV** module, the word `Lord` is never marked with a **w** element for the Strong's number `H3068` - not even for any **w** element whatsoever.

The extracted data is as follows for the KJV:
```
00308	<divineName>God</divineName>
00001	<divineName>Jah</divineName>
00008	<divineName>Jehovah</divineName>
06517	<divineName>Lord</divineName>
00110	<divineName>Lord’s</divineName>
```

For STV.xml the extracted data is:
```
00004	<divineName><w lemma="strong:G1203">Heere</w></divineName>
00001	<divineName><w lemma="strong:G1413">Heere</w></divineName>
00002	<divineName><w lemma="strong:G2960">Heeren</w></divineName>
00004	<divineName><w lemma="strong:G2962">heeren</w></divineName>
00670	<divineName><w lemma="strong:G2962">Heeren</w></divineName>
00001	<divineName><w lemma="strong:G80">Heeren</w></divineName>
00040	<divineName><w lemma="strong:H113">Heere</w></divineName>
00431	<divineName><w lemma="strong:H136">Heere</w></divineName>
00027	<divineName><w lemma="strong:H3050">Heere</w></divineName>
06462	<divineName><w lemma="strong:H3068">Heere</w></divineName>
00305	<divineName><w lemma="strong:H3069">Heere</w></divineName>
00001	<divineName><w lemma="strong:H3519">Heeren</w></divineName>
00001	<divineName><w lemma="strong:H3548">Heeren</w></divineName>
00005	<divineName><w lemma="strong:H430">Heere</w></divineName>
00002	<divineName><w lemma="strong:H4756">Heere</w></divineName>
00001	<divineName><w lemma="strong:H5650">Heeren</w></divineName>
00001	<divineName><w lemma="strong:H6635">Heeren</w></divineName>
```
_Originally posted by @DavidHaslam in https://github.com/Isidore-Guild/statenvertaling/issues/8#issuecomment-668834737_

**Comment by lemtom** [comment]
Quick initial check with Strong's dictionaries and their KJV translations:

G1203 (Lord, master), G1413 (Potentate, Prince, but used to refer to God), G2960 (belonging to the Lord, in older Dutch as a grammatical case), G2962 (Master, lord -- maybe the lowercase version should not be tagged with divineName though), H113 (Lord, sir), H3050 (Lord, Jah), H136 (Lord, of the Lord), H3068 (Lord, God Jehovah), H3069 (God, Lord), H430 (God, god), H4756 (Lord, of God, of King), 

G80, H3519, H3548, H5650 and H6635 seem incorrect. Will look into that. My guess is that something like "(noun) of the lord" being parsed as "noun (of the lord)" happened, as all forms are in an old grammatical case.

**Comment by lemtom** [comment]
- `<w lemma="strong:H3068">priesteren</w> des <divineName><w lemma="strong:H3548">Heeren</w></divineName>`
- `<w lemma="strong:G2962">broeder</w> des <divineName><w lemma="strong:G80">Heeren</w></divineName>`
- `<w lemma="strong:H3068">heerlijkheid</w> des <divineName><w lemma="strong:H3519">Heeren</w></divineName>`
- `<w lemma="strong:H3068">knecht</w> des <divineName><w lemma="strong:H5650">Heeren</w></divineName>`
- `<w lemma="strong:H3068">heir</w> des <divineName><w lemma="strong:H6635">Heeren</w></divineName>`
These are swapped, probably due to the regular expression having picked the wrong word to align with.

**Comment by DavidHaslam** [comment]
It's a rule in OSIS that one should only use the **divineName** element to mark the translation (or transliteration) of the Hebrew [tetragrammaton](https://en.wikipedia.org/wiki/Tetragrammaton) and its cognate form `Jah`.

This means that it's not to be used for the occurrences of `Lord` or `Heere` found in translations of the Greek NT - or for that matter the Greek DC books from the LXX.

**Comment by lemtom** [comment]
This should be resolved now.

**Comment by DavidHaslam** [comment]
Thanks. @lemtom 

I'll hold on before doing the next download in view of the further issues I added - especially #13

**Comment by LAfricain** [comment]
Hello,
I have still an issue during validation. Can you have a look?


```
xmllint --noout --schema ~/.bin/osisCore.2.1.1.xsd STV.xml 

STV.xml:25131: element divineName: Schemas validity error : Element '{http://www.bibletechnologies.net/2003/OSIS/namespace}divineName': This element is not expected. Expected is one of ( {http://www.bibletechnologies.net/2003/OSIS/namespace}a, {http://www.bibletechnologies.net/2003/OSIS/namespace}index, {http://www.bibletechnologies.net/2003/OSIS/namespace}note, {http://www.bibletechnologies.net/2003/OSIS/namespace}seg ).
STV.xml fails to validate

```
The right way to write it is:
```
 <divineName><w lemma="strong:H3068">Heeren</w></divineName>
```

**Comment by DavidHaslam** [comment]
Simples!

The BibleTechnologies site went AWOL several years ago.

There’s a copy of the .xsd file somewhere on the CrossWire server.
Check the wiki for precise details.

https://wiki.crosswire.org/

Aside: Using a local copy would also be faster.

Best regards,

David Haslam

**Comment by LAfricain** [comment]
Hi David,
No the problem is not the validation, but the osis file. <divineName> seems to be wrong placed.

**Comment by LAfricain** [comment]
With the changes in my new pull request the osis validates.
